M48
; DRILL file {KiCad (6.0.2)} date Thu Nov  3 13:32:59 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-03T13:32:59+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.4173Y-2.7362
X6.4173Y-3.9961
X8.2874Y-2.7362
X8.2874Y-3.9961
T0
M30
