M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Thu 13 Oct 2022 03:27:09 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-13T03:27:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X163.0Y-69.5
X163.0Y-101.5
X210.5Y-69.5
X210.5Y-101.5
T0
M30
