M48
; DRILL file {KiCad (6.0.2)} date Thu Oct 13 14:06:46 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-13T14:06:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.5827Y-2.2835
X3.5827Y-3.8189
X6.1339Y-2.2835
X6.1339Y-3.8189
T0
M30
